name: BuildTeam
main: net.buildtheearth.Main
api-version: 1.12
version: 0.1.3-alpha
author: MineFact, frikandelworst, George112n, ELgamer

commands:
  buildteam:
    description: Main command of the Build Team plugin
    usage: /buildteamtools
    aliases: [btt]
  generate:
    description: Generator tool of BuildTheEarth
    usage: /generate
    aliases: [gen, g]
  navigator:
    description: Opens the universal navigator
    usage: /navigator
    aliases:
      - nav
      - navigate
  warp:
    description: Command for managing warps.
    usage: /warp <subcommand>
    aliases:
      - warps