name: BuildTeam
main: net.buildtheearth.Main
api-version: 1.12
version: 1.0.1
author: MineFact

commands:
  buildteam:
    description: Main command of the Build Team plugin
    usage: /buildteam
  generator:
    usage: /generator