name: BuildTeam
main: net.buildtheearth.Main
api-version: 1.12
version: 0.1.0-alpha
author: MineFact

commands:
  buildteam:
    description: Main command of the Build Team plugin
    usage: /buildteam
  generate:
    description: Generator tool of BuildTheEarth
    usage: /generate
    aliases: [gen, g]
