# ----------------------------------------------------------------------------------------------
# |                BuildTeamTools - Navigation Module - by BuildTheEarth
# ----------------------------------------------------------------------------------------------
# | The navigator module allows the player to navigate through the project
# ----------------------------------------------------------------------------------------------
# | [Github Repo]           https://github.com/BuildTheEarth/BuildTeamTools
# | [Config Documentation]  https://github.com/BuildTheEarth/BuildTeamTools/wiki/Configuration
# | [Contacts - Discord]    BuildTheEarth Staff Discord, @minefact
# ----------------------------------------------------------------------------------------------


# Configures the navigator item in the players hotbar
navigator-hotbar-item:
  # Enables or disables the navigator hotbar item [true|false]
  nav-enabled: true
  # The hotbar slot into which the navigator item should be placed
  nav-slot: 0

# Specifies which menu items should be enabled
main-menu-items:
  # Configures the build item inside the navigator
  build-item:
    # Enables or disables the build item inside the navigator [true|false]
    build-enabled: true
    # (Optional) Execute a custom command or send a message when the build item is clicked [/command|message]
    build-action: /command
  # Configures the tutorial item inside the navigator
  tutorial-item:
    # Enables or disables the tutorial item inside the navigator [true|false]
    tutorial-enabled: false
    # (Optional) Execute a custom command or send a message when the tutorial item is clicked [/command|message]
    tutorial-action: /command



# NOTE: Do not change
config-version: 1.4